meta_product_name: "Rec It BIG"
meta_title: "Rec It BIG - Record your idea before it goes !"
meta_description: "Rec It BIG is a musical app designed for singer artist so they can capture their inspirationnal moments"
meta_image: "og_image_rec_it.png" # should exist in `app/assets/images/`
